### ISSUE TITLE
Adding 'newly created' targets

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#12]
Hi Brock, we've added a new target, 5.d, that is not in the National list.  I've added it in the global_targets.yml file, but wanted to make sure it would automatically align properly on the site.  Indicators also need to be created for this new target.

**Comment by dawncomer** [comment]
@brockfanning

**Comment by brockfanning** [comment]
Sounds good @dawncomer, I don't think there is anything else you need to do for the target, but as you say the indicators need to be created. I think that is probably a 3-step process:
1. Create a new file in [this folder](https://github.com/dawncomer/open-sdg-site-starter/tree/develop/_indicators)
1. Create a new file in [this folder](https://github.com/dawncomer/open-sdg-data-starter/tree/develop/meta)
1. Create a `global_indicators.yml` file in [this folder](https://github.com/dawncomer/open-sdg-site-starter/tree/develop/data/translations/en) and populate it accordingly.

This seems like a good topic for some new documentation!

**Comment by dawncomer** [comment]
Hi @brockfanning, I agree a good topic for new documentation.  
FYI, I also had to create a new file in [this folder](https://github.com/dawncomer/open-sdg-data-starter/tree/develop/data) for the site to process without errors.  The new target is not yet showing, but I'll check after the evening build to see if it's there.

**Comment by brockfanning** [comment]
@dawncomer Ah yes, so it's a 4-step process - thanks for catching that. Let me know if it still doesn't show up after the next site build.

**Comment by dawncomer** [comment]
Hi @brockfanning no problem.  So the target content is showing, however the text that I've included for indicator is not showing on the main page for the goal 
![5 d 1 indicator main page](https://user-images.githubusercontent.com/46500838/51646164-5107d280-1f2c-11e9-899c-3e779db99d48.PNG),  however, the text does show up in 'global metadata indicator name' field on the indicator page (note that TBD is noted in the 'indicator name' field, but not within the red banner. 
![5 d 1 indicator name metadata page](https://user-images.githubusercontent.com/46500838/51646188-667cfc80-1f2c-11e9-89b3-fc428929f8be.PNG).  
I made edits in this [file](https://github.com/dawncomer/open-sdg-data-starter/blob/develop/meta/5-d-1.md).   Is there a central location from where the 'indicator' language is being pulled?

**Comment by brockfanning** [comment]
@dawncomer I think the missing piece is step 3 above, creating a "global_indicators.yml" file. I've submitted a PR that should get you started: https://github.com/dawncomer/open-sdg-site-starter/pull/14

**Comment by dawncomer** [comment]
@brockfanning for my understanding, how does this file differ from the global_indicators.yml file we've already created?

**Comment by brockfanning** [comment]
Actually what we added before was for targets, and this new one is for indicators - two different files.

**Comment by dawncomer** [comment]
@brockfanning got it, thanks!
This worked.

**Comment by dawncomer** [comment]
Hi @brockfanning 
I'm updating the site, reverting target 5.d and indicator 5.d.1 to 5.x and 5.x.1.  I've made changes in each related file, but am stumped by this [error](https://circleci.com/gh/dawncomer/open-sdg-data-starter/2745).   I checked each file in our 4-step process noted above.  

UPDATE: I reverted the files I changed from 5.d to 5.x back to 5.d (everything passed circle ci, then  created new 5.x target and indicator files.  I'm still experiencing this [error](https://circleci.com/gh/dawncomer/open-sdg-data-starter/2754) when creating the 5-x-1.md file

Appreciate your guidance.

Thanks!
Dawn

**Comment by brockfanning** [comment]
Hi @dawncomer is this happening after pressing the "Rebuild" button in CircleCI, by any chance?

**Comment by dawncomer** [comment]
Hi @brockfanning, it is not.   It's happening after committing the new files.

**Comment by brockfanning** [comment]
From what I can see, that last error you linked to should not be happening anymore. Can you try making a new change to trigger a build? (any change will trigger a build)

**Comment by brockfanning** [comment]
@dawncomer Note I'm talking about the data repository.

**Comment by dawncomer** [comment]
HI @brockfanning I just made changes to the .csv and .md files in 5.d.1 and both builds ran successfully.

**Comment by brockfanning** [comment]
Great, sounds like you're all set.

For future reference, I think this is what is happening:

1. When there is a data file for an indicator, but no metadata file, the build will fail.
2. When there is a metadata file for an indicator, but no data file, the build will fail.
3. When there is both a data file and a metadata file for an indicator, the build will succeed.

So I think the options are:

1. Go ahead and create the data/metadata files one-at-a-time, as you are now. Expect that the first build will fail, and the second build will succeed.
2. Get a bit more advanced with Git and/or Github, and add the data/metadata files at the same time. In this case there would be only one build, which would succeed. (In a nutshell, with this approach you're adding multiple changes to one "branch".)

By the way, [this course on Git](https://www.lynda.com/Git-tutorials/Git-Essential-Training/100222-2.html) was enormously helpful for me personally. I highly recommend it.

**Comment by dawncomer** [comment]
ok, @brockfanning got it!  also, I see my other error was that I was looking at our City production site when checking for the changes to show vs. looking at [my GitHub site](https://dawncomer.github.io/open-sdg-site-starter/5/).  I see that 5.x is showing on the site.   This is a process change I also have to get used to when committing changes.  Thanks so much!

**Comment by dawncomer** [comment]
@angelamhkim

**Comment by angelamhkim** [comment]
@brockfanning and @dawncomer 
I also tried creating a new indicator (3.4.3) - not a new target - and am getting this [error](https://circleci.com/gh/dawncomer/open-sdg-site-starter/667). I created [csv](https://github.com/dawncomer/open-sdg-data-starter/blob/develop/data/indicator_3-4-3.csv) and [md](https://github.com/dawncomer/open-sdg-data-starter/edit/develop/meta/3-4-3.md) files in the data repository as well as an [md](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/_indicators/3-4-3.md) file in the site repository and changes to the [global_indicators.yml](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/data/translations/en/global_indicators.yml). It is showing up in the [site](https://dawncomer.github.io/open-sdg-site-starter/3/) but as 3.4.2 instead of the newly created 3.4.3

Am I missing anything?

**Comment by angelamhkim** [comment]
@brockfanning and @dawncomer I'm still getting this [issue](https://circleci.com/gh/dawncomer/open-sdg-site-starter/670) with the newly created indicator 3.4,3. Everything looks fine on the site but the error keeps saying that 

internally linking to /open-sdg-site-starter/3-4-3, which does not exist

**Comment by angelamhkim** [comment]
the new updates make it a lot easier to create new indicators. 
1) add the text here [here](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/data/translations/en/global_indicators.yml)
2) create a new csv file [here ](https://github.com/dawncomer/open-sdg-data-starter/tree/develop/data)
3) create a new md file [here](https://github.com/dawncomer/open-sdg-data-starter/tree/develop/meta)
