### ISSUE TITLE
Tags on indicators

### ISSUE THREAD

**Issue by brockfanning** [dawncomer/open-sdg-site-starter#19]
Hi @dawncomer, in #13 we discussed possibly having "tags" display on indicators to identify them as "New", "Local", etc.. Is that still something you're interested in? The functionality is now baked into Open SDG, so it will be easy to add. I can submit a PR if you're still interested in that, but I'll need to know which specific tags you would like to be able to add.

**Comment by dawncomer** [comment]
Hi @brockfanning I think 'new' and 'localized' would be good.

thanks!
dawn

**Comment by dawncomer** [comment]
Hi @brockfanning, following up on this.  Let me know if the tagging functionality for 'new' and 'localized' is now available.

thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer Yep, we're ready to try this out. The first step would be a data update - and I've submitted a PR on the data repository to get us started: https://github.com/dawncomer/open-sdg-data-starter/pull/2

**Comment by brockfanning** [comment]
@dawncomer Ok, I've submitted a PR here, #30 to try this out.

**Comment by brockfanning** [comment]
@dawncomer Now you can check out the out-of-the-box tags of 5-5-1 and 5-d-1 [here](https://dawncomer.github.io/open-sdg-site-starter/5/). Next steps are either:

* Any feedback on visuals, desired changes, etc.
* Adding tags to other indicators

**Comment by dawncomer** [comment]
@brockfanning Nice! I like the tags.  ok, still working through the rest.  I will continue to provide feedback on the 2 notes above.  

is there a reason the domain changed?

**Comment by brockfanning** [comment]
We changed the paths of the goal pages from the short text, like "/no-poverty", "/climate-action", etc, to numbers like "/1", "/13", etc. This was partly for more predictable URLs (easier to type in), but mainly because the short text was tied to a separate project, sdg-translations, and we didn't want the risk of the paths changing unexpectedly. Numbers are also a nice language-agnostic standard to use.

**Comment by dawncomer** [comment]
Got it and will make a note of the domain change!  thanks!

**Comment by dawncomer** [comment]
Hi @brockfanning some updates on tags for our platform -  can we update the tags to the following:
replace 'new' with 'added'; replace 'localized' with 'revised'.  This naming will align with the rubric we've set up for how we've localized the goals.

Also, is there a way to also include the tags with the Targets?

Thanks!
Dawn

**Comment by brockfanning** [comment]
Hi Dawn, changing the tags is straightforward. They are in the metadata for each indicator. So you'd change in the "meta" folder of the data repository. For example you would change the "tags" field in this file, for example: https://github.com/dawncomer/open-sdg-data-starter/blob/develop/meta/5-d-1.md

Displaying tags on Targets is a cool idea, and not yet supported out-of-the-box. So this is another thing that would involve some coding (hack-a-thon task?). It does seem like a great candidate for eventually making it into Open SDG as an out-of-the-box feature, though.
