### ISSUE TITLE
Failed nightly build

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#20]
Hi @Brockfanning, the nightly run [failed](https://circleci.com/gh/dawncomer/open-sdg-site-starter/129) this evening, though I've not made any updates since Friday (everything ran smoothly [Friday evening - Sunday](https://circleci.com/gh/dawncomer)).   Have there been any changes to the source code that may have triggered this?

Thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer I had intended to "pin" to a particular version of Open SDG. What is happening is that development "upstream" in the Open SDG project is causing problems in your site. An easy way to avoid that is to control exactly which version of Open SDG you are using. This pull-request should accomplish that: #21

**Comment by dawncomer** [comment]
That worked!  thankS!
