### ISSUE TITLE
Target 8 Indicator alignment

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#22]
Hi @brockfanning.  I just noticed that [indicator 8.10.2](https://dawncomer.github.io/open-sdg-site-starter/decent-jobs-and-economic-growth/) is out of place.  Appreciate help with alignment.  Thanks!
![target 8](https://user-images.githubusercontent.com/46500838/53536444-50c69e00-3abb-11e9-8655-e13c8edf1f38.PNG)

**Comment by brockfanning** [comment]
Hi @dawncomer I think that will be an easy fix: in the 'meta' folder of the data repository, check the "target_id" field for this indicator. It looks like it's set to a target_id of 8.1, but it needs to be 8.10.

**Comment by dawncomer** [comment]
@brockfanning got it, fixed.  thanks!
