### ISSUE TITLE
Reporting Status change issue w/SDGs 11 & 16 

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#29]
Hi @brockfanning,
I made updates to the metadata files in SDG 11 & 16 yesterday, changing the reporting_status from notstarted to complete so that I can begin uploading and reviewing data.  

There were a few Circle CI [fails](https://circleci.com/gh/dawncomer/open-sdg-data-starter/1397) for some of the indicators in 11 and I've noticed that the reporting status on a few in [11](https://dawncomer.github.io/open-sdg-site-starter/sustainable-cities-communities/) and all in [16](https://dawncomer.github.io/open-sdg-site-starter/peace-and-justice-strong-institutions/) remain in 'exploring data sources' stage.

Any idea what may be happening?  I don't believe it's a nightly build update at this time since some of 11 changed status yesterday.

Thanks!

**Comment by brockfanning** [comment]
@dawncomer Just a shot in the dark, but you might try merge this PR as a first attempt: https://github.com/dawncomer/open-sdg-data-starter/pull/3

**Comment by dawncomer** [comment]
Thanks @brockfanning  
Question: should I check the code on other indicators to ensure the GH org was changed?  Or does this enable a universal change?

**Comment by dawncomer** [comment]
@brockfanning This worked, thanks!  
Let me know if a similar pr will have to be done when we activate other indicators.

**Comment by brockfanning** [comment]
@dawncomer That PR was a universal change on the data repository, so hopefully it should resolve the failures. The next step for us I think is that other PR over there: https://github.com/dawncomer/open-sdg-data-starter/pull/2. This will prepare the way for upgrading to Open SDG 0.5 and trying out some of the new features, like tags.

**Comment by dawncomer** [comment]
ok, done.  let me know if I've missed something @brockfanning   
Thanks!

**Comment by dawncomer** [comment]
Hi @brockfanning I attempted to change 11.3. back to 'notstarted' and rec'd the following error: https://circleci.com/gh/dawncomer/open-sdg-data-starter/1508

Thanks!
Dawn

**Comment by dawncomer** [comment]
@brockfanning disregard - I re-ran the build and it was successful.  thanks!
