### ISSUE TITLE
Target representation on site

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#3]
The current site layout does not show the target on the pages (https://connectingla1.github.io/open-sdg-site-starter/zero-hunger/).  We'd like to update the page layout to have the localized LA targets listed along with their corresponding indicators.  

Suggested layout from the un.org site:
![target visual a](https://user-images.githubusercontent.com/46500838/51006343-93c2b700-14f7-11e9-9854-82f25dd5c351.PNG)
Alternative option is to spread the text of the target the full width of the page and have the indicated at a sub-level.

With the addition of the target, it may also be useful to update the view of the hierarchy shown on the page.
![hierarchy](https://user-images.githubusercontent.com/46500838/51006535-7c37fe00-14f8-11e9-8a76-4bc38d84f4be.PNG)

We can discuss, thanks!

**Comment by dawncomer** [comment]
@brockfanning

**Comment by brockfanning** [comment]
@dawncomer As a first step I've create a PR, #6 to establish the central place where you would maintain the text of the localized targets. After you've merged that, feel free to start customizing them specifically for LA.

In the meantime, I've learned that this feature idea you've brought up (displaying targets on the platform) is also of interest to other countries, so I think this will be a great addition to the Open SDG platform. As such I'll be opening up a follow-up ticket on the open-sdg repo to continue discussion. Thanks for this idea!

**Comment by dawncomer** [comment]
Great! Thanks so much @brockfanning.  Let me know if there's any way I can help with target discussion.  I'm glad it's of interest for other countries.

**Comment by dawncomer** [comment]
Hi @brockfanning I rec'd an error on the last build, after merging PR #6
<img width="1204" alt="screen shot 2019-01-11 at 7 41 56 am" src="https://user-images.githubusercontent.com/46500838/51044641-69640e80-1576-11e9-8305-a16ef7660945.png">

**Comment by brockfanning** [comment]
Hi @dawncomer my hunch is that it's related to the username change. I'd recommend updating [this file](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/_config.yml) and find/replace "connectingLA1" with "dawncomer".

**Comment by dawncomer** [comment]
ah! yes, thank you that worked.  this helps as I learn how to decipher the errors in the code.

**Comment by brockfanning** [comment]
Great to hear. I just started [this issue](https://github.com/open-sdg/open-sdg/issues/55) to see maybe we can improve that error message.

**Comment by dawncomer** [comment]
Thanks!

**Comment by brockfanning** [comment]
@dawncomer I just submitted a PR, #9 with an attempt at this. There are screenshots there. Feel free to give feedback, or merge it if you think it will meet your needs.

**Comment by dawncomer** [comment]
Hi @brockfanning I've created a new file, open-sdg-site-starter/data/translations/en/localized_targets.yml to represent the localized targets, allowing us to keep the global_target file on hand and untouched in case needed in the future.  I attempted to see where this file is referenced in the code so that I could make the update, but was not successful.  Appreciate if you can update the code as needed with the new localized_targets.yml file where needed, and also it'd be helpful to learn/see where this update should occur in the site code.   I've updated about half of the targets, still have some remaining.  thx

**Comment by brockfanning** [comment]
@dawncomer I just submitted a PR that should fix it. One issue was that the LA-specific targets need to be in the global_targets.yml file, but also there was a bug that was preventing it from working. Try merging #11  and let me know if that helps.

**Comment by dawncomer** [comment]
@brockfanning thanks I will merge the PR. If need be, I can put the localized targets in the global_targets.yml file and a separate copy of the actual global targets in another file.  Let me know what is best.  thanks!

**Comment by brockfanning** [comment]
Hi @dawncomer there's no need to maintain a copy of the global targets here. You can just maintain the LA-specific overrides in the global_targets.yml file.

**Comment by dawncomer** [comment]
got it! thanks @brockfanning
