### ISSUE TITLE
trouble creating link

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#32]
Hi @brockfanning, i'm having trouble creating a link using this [coding method](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/data/translations/en/localization.yml), any ideas?  Here's the result:

<img width="1217" alt="Screen Shot 2019-05-07 at 3 32 19 PM" src="https://user-images.githubusercontent.com/46500838/57337233-72588d00-70dd-11e9-8b52-3233b757040a.png">

Thanks!

**Comment by dawncomer** [comment]
I used the same approach on [11.4](https://raw.githubusercontent.com/dawncomer/open-sdg-data-starter/develop/meta/11-4-1.md), but am not sure what's different above.

**Comment by brockfanning** [comment]
Yes, I think that's a quirk that may need clarification in the documentation. The content below the "---" in the metadata supports [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). But most other content (like the contents of localization.yml) does not support Markdown.

If you want to put a link in a place that doesn't support Markdown, you'll need to use HTML. So, instead of:

```
[here](http://sdglamayor.cityofla.acsitefactory.com)
```

...you would do this:

```
<a href="http://sdglamayor.cityofla.acsitefactory.com">here</a>
```

Obviously not as clean as the Markdown syntax, but at least it gets the job done.

**Comment by dawncomer** [comment]
thanks @brockfanning for the clarification.

**Comment by dawncomer** [comment]
@brockfanning something is happening with the spacing.  i've looked at the source code and can't quite figure it out.  Also, maybe the here can be underlined?   I've changed it to at this link...in case 'here' isn't obvious to folks.
<img width="1227" alt="Screen Shot 2019-05-08 at 3 16 26 PM" src="https://user-images.githubusercontent.com/46500838/57412080-608ded00-71a4-11e9-91b6-cb3686acebd0.png">

**Comment by brockfanning** [comment]
Hi @dawncomer yes this is a case where some CSS in Open SDG is causing an issue. There is CSS that was meant to be applied only to the goal icon, but is inadvertently affecting your link.

Probably the quickest way to resolve it would be to add some more custom CSS here: https://github.com/dawncomer/open-sdg-site-starter/blob/develop/assets/css/custom.scss#L5

For reference, here is the chunk of CSS that's affecting your link: https://github.com/open-sdg/open-sdg/blob/master/assets/css/default.scss#L555

**Comment by dawncomer** [comment]
Hi @brockfanning , I'm not following the steps to take to how to resolve this.  Can we do a walk-thru on CSS  Friday AM?
