### ISSUE TITLE
Typo on 16.2.3 (US & LA Site)

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#34]
Hi @Brockfanning,
FYI I noticed a typo on 16.2.3 on the [US site](https://sdg.data.gov/peace-and-justice-strong-institutions/) that carries over to the LA site... the indicator should read '...experienced sexual violence by age 18'  it currently reads 'by age 1' 
US Site:
![image](https://user-images.githubusercontent.com/46500838/58822610-c4150a00-85ec-11e9-9de7-516b82cd5e04.png)

LA Site:
![image](https://user-images.githubusercontent.com/46500838/58822649-da22ca80-85ec-11e9-8a41-dea4d7ed09d8.png)

Thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer I just put up a PR that should fix that: #35
