### ISSUE TITLE
City logo in the header image?

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#37]
Hi @Brockfanning
Is it possible to add the City logo on the site, to the left of the SDG Logo, as it has been done here for the US?

![image](https://user-images.githubusercontent.com/46500838/59141253-3162cb00-895e-11e9-8c88-20fc19701b6b.png)

Thanks!
Dawn

**Comment by dawncomer** [comment]
Hi @brockfanning
Let's use the LA SDG logo that's been designed.  Here's the image in png and pdf formats.  Let me know of problems adding to our site.

![toretti_lasdg_logo_main_lockup](https://user-images.githubusercontent.com/46500838/59396722-e5899a80-8d3e-11e9-9a21-72ef3a8daebe.png)

[toretti_lasdg_logo_main_lockup.pdf](https://github.com/dawncomer/open-sdg-site-starter/files/3283707/toretti_lasdg_logo_main_lockup.pdf)

Thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer I did a quick PR for this. All it took was having the file in a particular place, so that it overrides the default one.

https://github.com/dawncomer/open-sdg-site-starter/pull/44

**Comment by dawncomer** [comment]
Thanks @brockfanning .  I understand now where to make this update.

Regards,
Dawn
