### ISSUE TITLE
Font color on target localization comment added

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#4]
Hi @brockfanning, how do I code the font color to be white on the localization statement we added today? https://connectingla1.github.io/open-sdg-site-starter/no-poverty/

Also, hopefully I'm tagging you properly.  I couldn't seem to add you as an assignee.

Thanks!

**Comment by brockfanning** [comment]
@dawncomer That would be by adding to the custom.scss file with the particular style rules. I've submitted a PR to show what that would look like: #7

**Comment by dawncomer** [comment]
Thanks @brockfanning
