### ISSUE TITLE
13.2.1 not resolving properly on site

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#40]
Hi @brockfanning 
Can you help to see what may be going on here: https://prose.io/#dawncomer/open-sdg-data-starter/edit/develop/meta/13-2-1.md

Note how the code is showing on the site:
https://dawncomer.github.io/open-sdg-site-starter/13-2-1/

Thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer I just submitted a PR that should fix it: https://github.com/dawncomer/open-sdg-data-starter/pull/20

I think a few weeks ago an extra chunk of code got added to the metadata for that indicator, which caused the problem. In general, anything below the second "---" will display at the top of the page in a paragraph. Typically this is for showing a blurb about the indicator, or the state of the data, etc.

**Comment by dawncomer** [comment]
thanks @brockfanning this worked
