### ISSUE TITLE
straggling target on SDG 15

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#41]
Hi @brockfanning 
I've checked the global_targets.yml file and can't find a cause for this....
![image](https://user-images.githubusercontent.com/46500838/60225075-1804be80-983a-11e9-96d9-b25dc4d62e47.png)

any ideas?

thanks!
Dawn

**Comment by brockfanning** [comment]
@dawncomer I believe you need to fix the "target id" in the metadata. Right now it's just "15", but it needs to be "15.1".

https://github.com/dawncomer/open-sdg-data-starter/blob/develop/meta/15-1-1.md

**Comment by dawncomer** [comment]
got it, thanks @brockfanning
