### ISSUE TITLE
Circle CI build-deploy fails

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#47]
Hi @jwLACity @brockfanning 
Wanted to make sure you were aware of these fails:
https://circleci.com/gh/dawncomer/open-sdg-site-starter/387
https://circleci.com/gh/dawncomer/open-sdg-site-starter/381

i'm not sure if they were triggered when I made updates or due to other actions.

Thanks!
Dawn

**Comment by jwLACity** [comment]
Hi @dawncomer @brockfanning , let me take a look at it. I may have done something to have that fail. I will review everything, when you commit to `develop` and push that up to github, the built site should still be updated to github pages. I think the `gh-pages` branch is trying to run a `build` job.

**Comment by jwLACity** [comment]
@dawncomer @brockfanning , my workflow `build-deploy` is being ran in `gh-pages` branch. It is failing because it is missing the `_config.yml` and `_config_prod.yml`.

**Comment by jwLACity** [comment]
@dawncomer @brockfanning , Looking at the git history, we have not made any merges into `gh-pages` branch and I understand why we shouldn't. However, my changes to the circle-ci config appears to be propagated to the `gh-pages` branch and the changes requires config files not present in the branch, as they are in the `develop` and `aws` branch. Brock, I think we may need to change your deployment scripts to fix this issue? https://github.com/dawncomer/open-sdg-site-starter/tree/develop/scripts/deploy/circleci

**Comment by brockfanning** [comment]
@jwLACity It's possible that the [circleci config](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/.circleci/config.yml#L134) may need to have a `filters` section added under `build`, so that it only happens for the aws branch. Similar to the `filters` section under `deploy_s3`?

**Comment by jwLACity** [comment]
@brockfanning @dawncomer , Okay, we can try that route. Let me make a PR for this change.

**Comment by dawncomer** [comment]
Hi @jwLACity I accepted the PR and noted this comment.

Should I delete the noted branch?

<img width="922" alt="Screen Shot 2019-06-28 at 12 41 47 PM" src="https://user-images.githubusercontent.com/46500838/60367129-4f8e7a80-99a2-11e9-9313-8ab53be06a37.png">

**Comment by jwLACity** [comment]
Hi @dawncomer , you may delete it if you want. Deleting it or keeping it shouldn't affect us long term.

Verified there are no more failing builds under the branch `gh-pages`, closing.
