### ISSUE TITLE
Q on changing user name

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#5]
@brockfanning Am I at any risk by changing my username at this stage?   any redirect challenges?
![image](https://user-images.githubusercontent.com/46500838/51007251-a808b300-14fb-11e9-928e-affe58b39ac5.png)

Thanks!

**Comment by brockfanning** [comment]
@connectingLA1 I think it's fine to change your username at this point. The redirect thing is only really a big deal if you've already shared the URL with a lot of people and you don't want them to get confused when the old URL stops working.

**Comment by dawncomer** [comment]
@brockfanning great! thanks!
