### ISSUE TITLE
Is there a way to change the hyperlink font color?

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#57]
Hi @brockfanning 
I'm guessing the css files may aid with this, but is there a way to change the font color for the hyperlinked word 'link'...I'm thinking a yellow would work across all banner backgrounds?  Please advise...thanks!

![image](https://user-images.githubusercontent.com/46500838/60850724-6f455000-a1a5-11e9-96cc-a2b378173619.png)

**Comment by brockfanning** [comment]
Sure, in fact you've already got a spot in the CSS where it could go. Right under [this line](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/assets/css/custom.scss#L7) you could add something like `color: yellow` or whatever you'd like. You could also try something like `text-decoration: underline` which would underline the link.

**Comment by dawncomer** [comment]
Great! thanks @brockfanning.  This is working.
