### ISSUE TITLE
Updating reporting status view

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#59]
Hi @brockfanning 
Would love to update our reporting status page as the [UK](https://sustainabledevelopment-uk.github.io/reporting-status/) has done, showing only reported and exploring (Green and Red status).  Let me know how to incorporate this change.

thanks!
Dawn

**Comment by brockfanning** [comment]
See this line:
https://github.com/dawncomer/open-sdg-data-starter/blob/7a549cd3d451e17ae257e7e6b96c60d6d02261db/_prose.yml#L155

It has 4 items right now. You could delete 2 of them.

**Comment by dawncomer** [comment]
yes! this worked, thanks @brockfanning
