### ISSUE TITLE
unexpected theme folder error

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#60]
Hi @brockfanning,
Appreciate your help with this theme folder [error](https://circleci.com/gh/dawncomer/open-sdg-site-starter/454).

thanks!
dawn

**Comment by brockfanning** [comment]
@dawncomer Unfortunately the [YAML](https://yaml.org/) format is extremely sensitive about whitespace. Each indent has to be exactly right. See [this](https://github.com/dawncomer/open-sdg-site-starter/blob/develop/data/translations/en/global_targets.yml#L468) for an indentation issue.

**Comment by dawncomer** [comment]
thanks! this worked....
i'm actually having an issue adding 5.x and have re-opened Issue #12 to get your input.

Thanks!
