### ISSUE TITLE
recent changes not pushing to aws 

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#62]
Hi @brockfanning the recent changes made, adding [new 5.x target and indicator](https://dawncomer.github.io/open-sdg-site-starter/5/) are not pushing to the [aws production server](https://sdgdata.lamayor.org/5/) after completing the [PR](https://github.com/dawncomer/open-sdg-site-starter/pull/61).   @jwLACity has done the build locally:
Command to test in the 'aws' branch: bundle exec jekyll serve --config _config.yml,_config_prod.yml
Command to test in the `develop` branch: bundle exec jekyll serve.
however the changes are not reflected.  Any ideas on what may be happening?

Thanks!
Dawn

**Comment by brockfanning** [comment]
@jwLACity @dawncomer My first thought is maybe the caching layer -- is it possible that Cloudfront needs to be invalidated every time there is a production deployment?

**Comment by brockfanning** [comment]
@jwLACity @dawncomer But actually one other problem may be that the [data repository](https://github.com/dawncomer/open-sdg-data-starter/tree/aws) hasn't had a production deployment. Ie, the develop branch hasn't been merged to the aws branch, on the data repo.

**Comment by dawncomer** [comment]
@brockfanning @jwLACity let me try the 2nd option you've sent.  thanks

**Comment by dawncomer** [comment]
@brockfanning the recent changes are listed on this data repository PR[https://github.com/dawncomer/open-sdg-data-starter/compare/aws...develop](url)

Should I encounter any errors with merging the older commits listed?

@jwLACity fyi

**Comment by brockfanning** [comment]
Yes I'd go ahead with that PR.

**Comment by dawncomer** [comment]
@brockfanning   @jwLACity   completed the [PR](https://github.com/dawncomer/open-sdg-data-starter/pull/21)
No changes yet on aws production yet

**Comment by dawncomer** [comment]
ok, @brockfanning @jwLACity I made some additional changes to the localization.yml file, and after that build ran, the new 5.x target and indicator are now showing on the s3 bucket site.  not sure if that was the trigger or it was just a matter of waiting after PR #21 processed.

@jwLACity now it just needs a push to production and we should be set for our Thursday AM Launch.
you should see target/indicator 5.d and 5.d.1 replaced by 5.x and 5.x.1 on the Goal 5 page.

thanks!

**Comment by brockfanning** [comment]
Yes in general, the procedure for a production deployment might be something like:
1. Merge develop to aws on data repo
2. Wait 5 minutes
3. Merge develop to aws on site repo

@jwLACity Is there an additional step needed after this? Maybe with Cloudfront?

**Comment by dawncomer** [comment]
@brockfanning noted.  i'll be sure to do PR for data repo and site repo going forward.
@brockfanning and @jwLACity I just checked [sdgdata.lamayor](https://sdgdata.lamayor.org/5/), all changes have been pushed and look great!!!  thanks for your help getting us to today's launch!
