### ISSUE TITLE
jsonschema error

### ISSUE THREAD

**Issue by dawncomer** [dawncomer/open-sdg-site-starter#64]
Hi @brockfanning,
@angelamhkim has been working through our data platform with updates.  One  was to update the SDG metadata file link on 5.1.1 and we ran into an [error](https://circleci.com/gh/dawncomer/open-sdg-data-starter/2770) when the link was changed.  It's not making sense and appreciate your review and input on what might be happening.

We changed it, removed and returned it to the original link and the error persists.

Thanks so much!
Dawn

**Comment by brockfanning** [comment]
Hi Dawn, I just submitted a PR that might fix the problem: https://github.com/dawncomer/open-sdg-data-starter/pull/24

This pins the version of sdg-build to a particular version that did not use jsonschema. Eventually we'll figure out what is causing this error, but hopefully the resolves things in the short term.

**Comment by dawncomer** [comment]
Thanks @brockfanning, we'll give it a try!

**Comment by dawncomer** [comment]
@brockfanning this worked! thanks!
tagging @angelamhkim
